local api = {}
function api.convert(from)
    --[[
    this is the main conversion function, this powers the converter.
    ]]
    local line = from
        line = line:gsub("^%s*([%w_%.%[%]]+)%s*%-=%s*(.+)$", "%1 = %1 - %2")
        line = line:gsub("^%s*([%w_%.%[%]]+)%s*%*=%s*(.+)$", "%1 = %1 * %2") -- this converts stuff like -=, += *= to 1 = 1 * 2, whatever
        line = line:gsub("^%s*([%w_%.%[%]]+)%s*%+=%s*(.+)$", "%1 = %1 + %2")
        line = line:gsub("Instance%.new", "Instance.New")
        line = line:gsub("Vector3%.new", "Vector3.New")
        line = line:gsub("'Script'", "'ScriptInstance'")
        line = line:gsub("'ScreenGui'", "'GUI'")
        line = line:gsub("'Frame'", "'UIView'")
        line = line:gsub("game%.Players", "Players")
        line = line:gsub(":GetPlayers", "Players.PlayersConnected")
        line = line:gsub("'Explosion'", "--[[Use :CreateExplosion.]]")
        line = line:gsub(":GetPartsInPart", "--[[Not supported]]")
        line = line:gsub("game%.Lighting%.Fog%.(%w+)", "game['Environment'].Fog%1")
        line = line:gsub("game%.Lighting","Lighting")
        line = line:gsub("workspace%.Camera","Camera")
        line = line:gsub("StarterPlayer","PlayerDefaults")
        line = line:gsub("'ImageLabel'", "'UIImage'")
        line = line:gsub("(%w+)%.Position.=.(%w+)%.new(%d+,.%d+,.%d+)","%1:MovePosition(Vector3.New(%3, %4, %5))")
        line = line:gsub("%.BrickColor","--[[BrickColor is not supported in Polytoria]]")
        line = line:gsub("Enum%.Material","Enum.PartMaterial")
        line = line:gsub("'Texture'","--[[Textures are not supported in Polytoria]]")
        line = line:gsub("'Sparkles'","Particles")
        line = line:gsub("%.OnServerEvent",".InvokedServer")
        line = line:gsub("%.FireServer",".InvokeServer")
        line = line:gsub("%.FireAllClients",".InvokeClients")
        line = line:gsub("(%w+)%.InputBegan","Input.KeyDown")
        line = line:gsub("(%w+)%.InputEnded","Input.InputEnded")
        line = line:gsub("%.FireClient",".InvokeClient")
        line = line:gsub("%.OnClientEvent",".InvokedClient")
        line = line:gsub("'TextBox'","'UITextInput'")
        line = line:gsub("'UIListLayout'","'UIVerticalLayout'")
        line = line:gsub("Enum%.PartType","Enum.PartShape")
        line = line:gsub("Enum%.Font","Enum.TextFontPreset")
        line = line:gsub("%.TextYAlignment","Enum.TextVerticalAlign")
        line = line:gsub("Enum%.EasingStyle%.(%w+)","Enum.TweenType.easeOut%1")
        line = line:gsub("(%w+)%.AssemblyAngularVelocity.=.(%w+)%.new(%d+,.%d,.%d)","%1.AngularVelocity = Vector3.new(%3, %4, %5)")
        line = line:gsub("HttpService", "Http")
        line = line:gsub("ImageId", "ImageID")
        line = line:gsub("CastShadow", "CastShadows")
        line = line:gsub("RunService%.RenderStepped", "game.Rendered")
        line = line:gsub("'RemoteEvent'", "'Event'")
        line = line:gsub("task%.wait", "wait")
        line = line:gsub("'UserInputService'", "'Input'")
        line = line:gsub("%W.CFrame = CFrame.lookAt(%W, %W)", "%1:LookAt(%1, %2)")
        line = line:gsub("'TextButton'", "'UIButton'")
        line = line:gsub("'Script'", "'ScriptInstance'")
        line = line:gsub("Humanoid", "--[[Humanoids are not supported in Polytoria.]]")
        line = line:gsub("PathfindingService", "--[[Pathfinding is not supported in Polytoria]]")
        line = line:gsub("MarketplaceService", "--[[Marketplace services are not supported in Polytoria]]")
        line = line:gsub("Color3%.new(%d+,.%d+,.%d+)", "Color.New(%1, %2, %3)")
        line = line:gsub("workspace", "game['Environment']")
        line = line:gsub("game%.Players", "Players")
        line = line:gsub("DataStoreService", "Datastore")
        line = line:gsub("ServerScriptService", "ScriptService")
        line = line:gsub("game%.PlaceId", "game.GameID")
        line = line:gsub("CFrame%.new(%d+,.%d+,.%d+)", "Vector3.New(%1, %2, %3)")
        line = line:gsub("CFrame%.Angles(%d+,.%d+,.%d+)", "Vector3%.Angles(%1, %2, %3)")
        line = line:gsub("%.Rotation .= CFrame%.Angles(%W,.%W,.%W)", ":MoveRotation(Vector3.New(%1, %2, %3))")
    return line
end
return api